# This file was generated by GoReleaser. DO NOT EDIT.
class Para < Formula
  desc "A useful tool for software package manager analytics."
  homepage "https://github.com/halseylabs/para"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/halseylabs/para/releases/download/v0.2.0/para-v0.2.0-macos-amd64.tar.gz"
    sha256 "eb4e4fb49766d7a48349d4441c795d415915fce443fc637c4c34d893c341accd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/halseylabs/para/releases/download/v0.2.0/para-v0.2.0-linux-amd64.tar.gz"
      sha256 "71fa3f4e98023b29f44a58ce42df1c90c0a59ba5851d745e07027366cad3cb72"
    end
  end

  def install
    bin.install "para"
  end

  test do
    system "#{bin}/para", "help"
  end
end
