# This file was generated by GoReleaser. DO NOT EDIT.
class Para < Formula
  desc "A useful tool for software package manager analytics."
  homepage "https://github.com/halseylabs/para"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/halseylabs/para/releases/download/v0.4.0/para-v0.4.0-macos-amd64.tar.gz"
    sha256 "7f2acb7791462281162c7e9e9e0e596845691c0aced18a11081703bdf81ca465"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/halseylabs/para/releases/download/v0.4.0/para-v0.4.0-linux-amd64.tar.gz"
    sha256 "e8fb98a8b8fbdce677e22c231aa608975db9cab32c2bcde6eb97b06f08ce40cd"
  end

  def install
    bin.install "para"
  end

  test do
    system "#{bin}/para", "help"
  end
end
